/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/GOhfG8DdOC7
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";

export function Connect() {
  return (
    <section
      id="connect"
      className="flex text-semiWhite justify-center items-center bg-gray-100 dark:bg-gray-800 py-12 md:py-16 lg:py-20"
    >
      <div className="container px-4 md:px-6">
        <div className="max-w-3xl mx-auto text-center space-y-6">
          <h2 className="text-3xl font-Montserrat text-[#ccd6f6] font-bold tracking-tighter sm:text-4xl md:text-5xl">
            Connect with Me
            <span className="text-webGreen fadeAnimate">.</span>
          </h2>
          <div className="flex justify-center items-center space-x-6">
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="https://www.linkedin.com/in/avyuktsoni0731"
              target="_blank"
            >
              <LinkedinIcon />
              <span className="sr-only">LinkedIn</span>
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="https://www.twitter.com/SoniAvyukt"
              target="_blank"
            >
              <TwitterIcon />
              <span className="sr-only">Twitter</span>
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="https://github.com/avyuktsoni0731"
              target="_blank"
            >
              <GithubIcon />
              <span className="sr-only">GitHub</span>
            </Link>
          </div>
          <div className="space-y-2 font-Mono">
            <p className="text-gray-500 dark:text-gray-400">
              I&apos;d <span className="text-webRed">love</span> to hear from
              you<span className="text-webGreen">!</span> Feel free to reach out
              with any questions or just to say hello
              <span className="text-webGreen">.</span>
            </p>
            <p className="text-gray-500 dark:text-gray-400">
              Email:
              <a
                className="text-[#d2b94b] hover:underline dark:text-gray-50"
                href="mailto:ceo@avyuktsoni.co"
              >
                soniavyukt@gmail.com
              </a>
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

function GitlabIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.1 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z" />
    </svg>
  );
}

function LinkedinIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}

function TwitterIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  );
}

function GithubIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="currentColor"
    >
      <path d="M12 2C6.48 2 2 6.48 2 12c0 4.41 2.87 8.16 6.84 9.49.5.09.68-.22.68-.49 0-.24-.01-.88-.01-1.73-2.78.61-3.37-1.17-3.37-1.17-.45-1.15-1.11-1.46-1.11-1.46-.91-.63.07-.62.07-.62 1 .07 1.53 1.03 1.53 1.03.9 1.53 2.36 1.09 2.94.83.09-.65.35-1.09.63-1.34-2.22-.25-4.55-1.11-4.55-4.95 0-1.09.39-1.98 1.02-2.68-.1-.25-.45-1.27.1-2.65 0 0 .83-.27 2.75 1.02A9.57 9.57 0 0 1 12 6.8c.85.004 1.7.115 2.5.337 1.92-1.29 2.75-1.02 2.75-1.02.55 1.38.2 2.4.1 2.65.63.7 1.02 1.59 1.02 2.68 0 3.85-2.34 4.7-4.57 4.95.36.31.68.92.68 1.85 0 1.33-.01 2.4-.01 2.73 0 .27.18.58.69.48A10.004 10.004 0 0 0 22 12c0-5.52-4.48-10-10-10z" />
    </svg>
  );
}
