/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aYGDHfXuaMr
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import {
  CarouselItem,
  CarouselContent,
  Carousel,
  CarouselPrevious,
  CarouselNext,
} from "@/components/ui/carousel";
import Image from "next/image";

export function Projects2() {
  return (
    <section className="w-full py-12 md:py-16 lg:py-20">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center gap-4 md:gap-6 lg:gap-8">
          <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">
            My Projects
          </h2>
          <div className="relative w-full max-w-6xl">
            <Carousel className="w-full">
              <CarouselContent>
                <CarouselItem>
                  <div className="grid gap-4 md:grid-cols-2 lg:gap-6">
                    <Image
                      alt="Project 1"
                      className="aspect-video rounded-lg object-cover"
                      height={400}
                      src="/placeholder.svg"
                      width={600}
                    />
                    <div className="flex flex-col gap-2">
                      <h3 className="text-xl font-semibold">Project 1</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        A brief description of the first project in the
                        carousel.
                      </p>
                      <div className="mt-auto">
                        <Link
                          className="inline-flex items-center gap-2 rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                          href="#"
                        >
                          <ArrowRightIcon className="h-4 w-4" />
                          View Project
                        </Link>
                      </div>
                    </div>
                  </div>
                </CarouselItem>
                <CarouselItem>
                  <div className="grid gap-4 md:grid-cols-2 lg:gap-6">
                    <Image
                      alt="Project 2"
                      className="aspect-video rounded-lg object-cover"
                      height={400}
                      src="/placeholder.svg"
                      width={600}
                    />
                    <div className="flex flex-col gap-2">
                      <h3 className="text-xl font-semibold">Project 2</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        A brief description of the second project in the
                        carousel.
                      </p>
                      <div className="mt-auto">
                        <Link
                          className="inline-flex items-center gap-2 rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                          href="#"
                        >
                          <ArrowRightIcon />
                          View Project
                        </Link>
                      </div>
                    </div>
                  </div>
                </CarouselItem>
                <CarouselItem>
                  <div className="grid gap-4 md:grid-cols-2 lg:gap-6">
                    <Image
                      alt="Project 3"
                      className="aspect-video rounded-lg object-cover"
                      height={400}
                      src="/placeholder.svg"
                      width={600}
                    />
                    <div className="flex flex-col gap-2">
                      <h3 className="text-xl font-semibold">Project 3</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        A brief description of the third project in the
                        carousel.
                      </p>
                      <div className="mt-auto">
                        <Link
                          className="inline-flex items-center gap-2 rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                          href="#"
                        >
                          <ArrowRightIcon />
                          View Project
                        </Link>
                      </div>
                    </div>
                  </div>
                </CarouselItem>
              </CarouselContent>
            </Carousel>
            <CarouselPrevious className="absolute left-4 top-1/2 -translate-y-1/2 bg-white rounded-full p-2 shadow-md hover:bg-gray-100 dark:bg-gray-900 dark:text-white dark:hover:bg-gray-800">
              <ChevronLeftIcon />
            </CarouselPrevious>
            <CarouselNext className="absolute right-4 top-1/2 -translate-y-1/2 bg-white rounded-full p-2 shadow-md hover:bg-gray-100 dark:bg-gray-900 dark:text-white dark:hover:bg-gray-800">
              <ChevronRightIcon />
            </CarouselNext>
          </div>
        </div>
      </div>
    </section>
  );
}

function ArrowRightIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  );
}

function ChevronLeftIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  );
}

function ChevronRightIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  );
}
